version: "3.0"
services:
  jupyter:
    build:
      context: .
      dockerfile: docker/solo.Dockerfile
    volumes:
      - ./notebooks:/usr/src/notebooks
    ports:
      - "8888:8888"
      - "6006:6006"
